project:
  type: website
  output-dir: docs

website:
  title: "Massimo Aria"
  navbar:
    right:
      - text: About Me
        menu:
        - text: Short Bio
          file: shortbio.qmd
        - text: Curriculum Vitae
          file: cv.qmd
      - text: Research
        menu:
        - text: Publications
          file: publications.qmd
        - text: Projects
          file: projects.qmd
        - text: Software
          file: software.qmd
      - text: Teaching
        file: teaching.qmd
      - text: Photos
        file: photos.qmd
      - text: Contacts
        file: contacts.qmd
      - icon: book
        href: https://scholar.google.com/citations?user=Qu66YZQAAAAJ&hl=it
      - icon: globe
        href: https://www.researchgate.net/profile/Massimo-Aria
  page-footer:
    center: |
      © 2025 Massimo Aria – Built with [Quarto](https://quarto.org)

format:
  html:
    theme: spacelab
    includes:
      head: lightbox-head.html
    toc: true
    toc-location: left
    page-layout: full
    css: styles.css


