project:
  type: website
  output-dir: docs

website:
  title: "Massimo Aria"
  navbar:
    left:
      - text: About
        file: about.qmd
      - text: Publications
        file: publications.qmd
      - text: Teaching
        file: teaching.qmd
      - text: Projects
        file: projects.qmd
      - text: CV
        file: cv.qmd
      - text: Photos
        file: photos.qmd
      - text: Contacts & Links
        file: contacts.qmd
  page-footer:
    center: |
      © 2025 Massimo Aria – Built with [Quarto](https://quarto.org)

format:
  html:
    theme: superhero
    toc: true
    toc-location: left
    page-layout: full
    css: styles.css


