
---
title: "Publications"
format: html
---

This page presents a selection of my most relevant publications, organized by research area.  
For a complete list, please visit my <a href="https://scholar.google.com/citations?user=Qu66YZQAAAAJ" target="_blank">Google Scholar profile</a>.

---

## Monographs

1. Pagliara F., Aria M. & Mauriello M. (2025). **Models and Applications of Tourists’ Travel Behavior**. 1st Edition, Elsevier, <a href="https://doi.org/10.1016/C2023-0-01250-X" target="_blank">ISBN: 9780443265938</a>.  
<br>
2. Cuccurullo C., Aria M., Spano M. & D’Aniello L. (2023). **Leading Change in Academic Health Science Centers**. Zaccaria ed. ISBN: 9788899594213.  
<br>
---

## Journal Articles 

### Bibliometrics and Science Mapping

1. Aria, M., Cuccurullo, C. (2017). **bibliometrix: An R-tool for comprehensive science mapping analysis**. *Journal of Informetrics*, 11(4), 959–975, <a href="https://doi.org/10.1016/j.joi.2017.08.007" target="_blank"> DOI: 10.1016/j.joi.2017.08.007</a>.

2. Aria M., Angelelli M., Ciavolino E., Ringle, C.M., Sarstedt M. (2025). **Conceptual structure and thematic evolution in partial least squares structural equation modeling research**. *Quality & Quantity*, <a href="https://doi.org/10.1007/s11135-025-02071-4" target="_blank"> DOI: 10.1007/s11135-025-02071-4</a>.

3. Aria, M., Cuccurullo, C., D’Aniello, L., Misuraca, M., & Spano, M. (2024). **Comparative science mapping: a novel conceptual structure analysis with metadata**. *Scientometrics*, <a href="https://doi.org/10.1007/s11192-024-05161-6" target="_blank"> DOI: 10.1007/s11192-024-05161-6</a>.

4. Aria, M., Le, T., Cuccurullo, C., Belfiore, A., & Choe, J. (2024). **openalexR: An R-Tool for Collecting Bibliometric Data from OpenAlex**. *The R Journal*, <a href="https://doi.org/10.32614/RJ-2023-089" target="_blank"> DOI: 10.32614/RJ-2023-089</a>.

5. Ciavolino, E., Aria, M., Cheah, J. H., & Roldán, J. L. (2022). **A tale of PLS Structural Equation Modelling: Episode I— A Bibliometrix Citation Analysis**. *Social Indicators Research*, <a href="https://doi.org/10.1007/s11205-022-02994-7" target="_blank"> DOI: 10.1007/s11205-022-02994-7</a>.

6. D’Aniello L., Spano M., Cuccurullo C., Aria M. (2022). **Academic Health Centers’ configurations, scientific productivity, and impact: Insights from the Italian setting**. *Health Policy*, <a href="https://doi.org/10.1016/j.healthpol.2022.09.007" target="_blank"> DOI: 10.1016/j.healthpol.2022.09.007</a>.

7. Belfiore, A., Cuccurullo, C., & Aria, M. (2022). **IoT in healthcare: A scientometric analysis**. *Technological Forecasting and Social Change*, 184, <a href="https://doi.org/10.1016/j.techfore.2022.122001" target="_blank"> DOI: 10.1016/j.techfore.2022.122001</a>.

8. Aria M., Misuraca M., Spano M. (2020). **Mapping the Evolution of Social Research and Data Science on 30 Years of Social Indicators Research**. *Social Indicators Research*, <a href="https://doi.org/10.1007/s11205-020-02281-3" target="_blank"> DOI: 10.1007/s11205-020-02281-3</a>.  


---

### Statistics and Machine Learning

1. Aria M., Gnasso A., Iorio C., Pandolfo, G. (2023). **Explainable Ensemble Trees**. *Computational Statistics*, <a href="https://doi.org/10.1007/s00180-022-01312-6" target="_blank"> DOI: 10.1007/s00180-022-01312-6</a>.

2. Aria, M., Cuccurullo C, D'Aniello L, Misuraca M., Spano M. (2022). **Thematic Analysis as a New Culturomic Tool: The Social Media Coverage on COVID-19 Pandemic in Italy**. *Sustainability*, 14(6), 3643, <a href="https://doi.org/10.3390/su14063643" target="_blank"> DOI: 10.3390/su14063643</a>.

3. Pandolfo G., Iorio C., Staiano M., Aria M., Siciliano R. (2021). **Multivariate process control charts based on the Lp depth**. *Applied Stochastic Models in Business and Industry*, <a href="https://doi.org/10.1002/asmb.2616" target="_blank"> DOI: 10.1002/asmb.2616</a>.

4. Aria M., Cuccurullo C., Gnasso A. (2021). **A comparison among interpretative proposals for Random Forests**. *Machine learning with Applications*, <a href="https://doi.org/10.1016/j.mlwa.2021.100094" target="_blank"> DOI: 10.1016/j.mlwa.2021.100094</a>.

5. Iorio C., Aria M., D'Ambrosio A., Siciliano R. (2019). **Informative Trees by Visual Pruning**. *Expert Systems with Applications*, <a href="https://doi.org/10.1016/j.eswa.2019.03.018" target="_blank"> DOI: 10.1016/j.eswa.2019.03.018</a>.

6. Aria M., D'Ambrosio A., Iorio C., Siciliano R., Cozza V. (2018). **Dynamic recursive tree-based partitioning for malignant melanoma identification in skin lesion dermoscopic images**. *Statistical Papers*, <a href="https://doi.org/10.1007/s00362-018-0997-x" target="_blank"> DOI: 10.1007/s00362-018-0997-x</a>.

7. Siciliano R., D'Ambrosio A., Aria M., Amodio S. (2017). **Analysis of Web Visit Histories, Part II: Predicting Navigation by Nested STUMP Regression Trees**. *Journal of Classification*, <a href="https://doi.org/10.1007/s00357-017-9239-5" target="_blank"> DOI: 10.1007/s00357-017-9239-5</a>.

8. D’Ambrosio A., Aria M., et al. (2017). **Regression trees for multivalued numerical response variables**. *Expert Systems with Applications*, 69, 1339–1351, <a href="https://doi.org/10.1016/j.eswa.2016.10.021" target="_blank"> DOI: 10.1016/j.eswa.2016.10.021</a>.

9. Siciliano R., D'Ambrosio A., Aria M., Amodio S. (2016). **Analysis of Web Visit Histories, Part I: Distance-Based Visualization of Sequence Rules**. *Journal of Classification*, <a href="https://doi.org/10.1007/s00357-016-9204-8" target="_blank"> DOI: 10.1007/s00357-016-9204-8</a>.

10. D’Ambrosio A., Aria M., et al. (2012). **Accurate Tree-based Missing Data Imputation and Data Fusion within the Statistical Learning Paradigm**. *Journal of Classification*, 29(2), 227–258, <a href="https://doi.org/10.1007/s00357-012-9108-1" target="_blank"> DOI: 10.1007/s00357-012-9108-1</a>.

11. Aria, M. (2009). **Parallel networks for compositional longitudinal data**. *Italian Journal of Applied Statistics*, 20(1), 5–20.

---

### Tourism, Management, Transportation, and Social Sciences

1. Belfiore A., Cuccurullo C., Aria M. (2022). **Financial configurations of Italian private hospitals: an evolutionary analysis**. *Health Policy*, <a href="https://doi.org/10.1016/j.healthpol.2022.05.004" target="_blank"> DOI: 10.1016/j.healthpol.2022.05.004</a>.

2. Pagliara F., Aria M., Russo L. (2021). **Measuring retailers’ perceptions of new metro stations inauguration**. *Land Use Policy*, <a href="https://doi.org/10.1016/j.landusepol.2021.105349" target="_blank"> DOI: 10.1016/j.landusepol.2021.105349</a>.

3. Della Corte V., Aria M., Del Gaudio G., Barney J.B., Cobanoglu C., Sepe F. (2021). **The relevance of relational capabilities in collaborative decisions**. *International Journal of Contemporary Hospitality Management*, <a href="https://doi.org/10.1108/ijchm-01-2021-0037" target="_blank"> DOI: 10.1108/ijchm-01-2021-0037</a>.

4. Pagliara F., Aria M., et al. (2020). **A theoretical model linking the development of the transportation system with citizens' trust in government actors**. *Papers in Regional Science*, <a href="https://doi.org/10.1111/pirs.12570" target="_blank"> DOI: 10.1111/pirs.12570</a>.

5. Pagliara F., Russo L., Aria M., et al. (2020). **Validating a theoretical model of citizens’ trust in tourism development**. *Socio-Economic Planning Sciences*, <a href="https://doi.org/10.1016/j.seps.2020.100922" target="_blank"> DOI: 10.1016/j.seps.2020.100922</a>.

6. Allini A., Aria M., et al. (2018). **Motivations behind users’ participation in the standard-setting process: Focus on financial analysts**. *Journal of Accounting and Public Policy*, <a href="https://doi.org/10.1016/j.jaccpubpol.2018.04.002" target="_blank"> DOI: 10.1016/j.jaccpubpol.2018.04.002</a>.

7. Aria M., Gaeta G.L., Marani U. (2018). **Similarities and Differences in Competitiveness Among European NUTS2 Regions: An Empirical Analysis Based on 2010–2013 Data**. *Social Indicators Research*, <a href="https://doi.org/10.1007/s11205-018-1909-0" target="_blank"> DOI: 10.1007/s11205-018-1909-0</a>.

8. Della Corte V., Aria M., Del Gaudio G. (2018). **Strategic governance in tourist destinations**. *International Journal of Tourism Research*, <a href="https://doi.org/10.1002/jtr.2192" target="_blank"> DOI: 10.1002/jtr.2192</a>.

9. Della Corte V., Aria M. (2014). **Why strategic networks often fail. Some empirical evidence from the area of Naples**. *Tourism Management*, 45, 3–15, <a href="https://doi.org/10.1016/j.tourman.2014.03.010" target="_blank"> DOI: 10.1016/j.tourman.2014.03.010</a>.

10. Galante, F., Mauriello, F., Montella, A., Pernetti, M., Aria, M., & D’Ambrosio, A. (2010). **Traffic calming along rural highways crossing small urban communities: Driving simulator experiment**. *Accident Analysis & Prevention*, 42(6), 1585-1594, <a href="https://doi.org/10.1016/j.aap.2010.03.017" target="_blank"> DOI: 10.1016/j.aap.2010.03.017</a>.
